kind: Cluster
#specifies type of cluster
apiVersion: kind.x-k8s.io/v1alpha4
#version of the kind configkubectl get
nodes:
  - role: control-planec
  - role: worker
  - role: worker
  - role: worker
    extraPortMappings:
        - containerPort: 80
          hostPort: 80
          listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
          protocol: udp # Optional, defaults to tcp

name:
networking:
  podSubnet:
